plugins:
  algolia_enabled:
    default: false
    client: true
  algolia_autocomplete_enabled:
    default: false
    client: true
  algolia_answers_enabled:
    default: false
    client: true
  algolia_application_id:
    default: ""
    client: true
  algolia_search_api_key:
    default: ""
    client: true
  algolia_admin_api_key:
    default: ""
    client: false
    secret: true
  algolia_discourse_username:
    default: "system"
    client: false
